# Generated by Django 4.2.5 on 2023-09-21 07:26

from django.db import migrations, models
import dogtag.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DogInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_nickname', models.CharField(max_length=50)),
                ('dog_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('birth_year', models.CharField(blank=True, max_length=4, null=True)),
                ('gender', models.CharField(choices=[('M', '남아'), ('F', '여아')], max_length=1)),
                ('is_neutered', models.BooleanField(default=False)),
                ('dog_image', models.ImageField(blank=True, null=True, upload_to=dogtag.models.get_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
